#!/usr/bin/env python3
"""Extract DOOM intermission-screen glyphs from the shareware WAD.

Reads DOOM/DOOM1.WAD out of public/game/doom.zip and emits a compact TypeScript
module (src/game/doomGlyphs.ts) containing:
  - the game palette (PLAYPAL, first page)
  - the big-number font used on the "FINISHED" stats screen (WINUM0..9),
    the percent sign (WIPCNT) and colon (WICOLON)
  - the Episode-1 level-name banners (WILV00..WILV08) for level detection

Each glyph is stored as its opaque pixels ([x, y, paletteIndex, ...]) plus size
and draw offsets, so the runtime reader can match them pixel-exactly against the
DOOM canvas (which renders at an exact 2x integer scale, nearest-neighbour).

Run once and commit the generated file:  python scripts/extract-glyphs.py
"""
import io
import struct
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZIP = ROOT / "public" / "game" / "doom.zip"
OUT = ROOT / "src" / "game" / "doomGlyphs.ts"

# Lumps we need. Level banners WILV00..08 = E1M1..E1M9.
WANTED = (
    ["PLAYPAL"]
    + [f"WINUM{i}" for i in range(10)]
    + ["WIPCNT", "WICOLON", "WIMINUS"]
    + [f"WILV0{i}" for i in range(9)]
)


def read_wad_from_zip() -> bytes:
    with zipfile.ZipFile(ZIP) as z:
        return z.read("DOOM/DOOM1.WAD")


def parse_directory(wad: bytes):
    ident, numlumps, infoofs = struct.unpack_from("<4sii", wad, 0)
    lumps = {}
    order = []
    for i in range(numlumps):
        filepos, size, raw = struct.unpack_from("<ii8s", wad, infoofs + i * 16)
        name = raw.split(b"\x00", 1)[0].decode("ascii", "replace")
        lumps[name] = (filepos, size)
        order.append(name)
    return lumps, order


def decode_patch(data: bytes):
    """Decode a DOOM patch (picture) lump -> (w, h, xoff, yoff, [(x, y, idx)])."""
    w, h, xoff, yoff = struct.unpack_from("<hhhh", data, 0)
    coloffs = struct.unpack_from("<%di" % w, data, 8)
    pixels = []
    for x in range(w):
        pos = coloffs[x]
        while True:
            topdelta = data[pos]
            if topdelta == 0xFF:
                break
            length = data[pos + 1]
            pos += 3  # skip topdelta, length, unused-pre byte
            for row in range(length):
                idx = data[pos + row]
                pixels.append((x, topdelta + row, idx))
            pos += length + 1  # skip pixels + unused-post byte
    return w, h, xoff, yoff, pixels


def main():
    wad = read_wad_from_zip()
    lumps, _order = parse_directory(wad)

    # Palette (first page = 256 * 3 bytes).
    pp, psz = lumps["PLAYPAL"]
    palette = list(wad[pp : pp + 768])

    glyphs = {}
    for name in WANTED:
        if name == "PLAYPAL":
            continue
        if name not in lumps:
            print(f"  ! missing lump {name}")
            continue
        pos, size = lumps[name]
        w, h, xoff, yoff, px = decode_patch(wad[pos : pos + size])
        flat = []
        for (x, y, idx) in px:
            flat.extend((x, y, idx))
        glyphs[name] = dict(w=w, h=h, xoff=xoff, yoff=yoff, px=flat)
        print(f"  {name}: {w}x{h} off=({xoff},{yoff}) opaque={len(px)}")

    # Emit TypeScript.
    lines = []
    lines.append("// AUTO-GENERATED by scripts/extract-glyphs.py — do not edit by hand.")
    lines.append("// DOOM intermission-screen glyphs extracted from shareware DOOM1.WAD.")
    lines.append("")
    lines.append("export type Glyph = {")
    lines.append("  w: number;")
    lines.append("  h: number;")
    lines.append("  xoff: number;")
    lines.append("  yoff: number;")
    lines.append("  /** flat opaque pixels: [x, y, paletteIndex, ...] */")
    lines.append("  px: number[];")
    lines.append("};")
    lines.append("")
    lines.append("/** DOOM PLAYPAL page 0: 256 RGB triplets, flat (r,g,b,...). */")
    lines.append("export const PALETTE: readonly number[] = " + compact(palette) + ";")
    lines.append("")
    lines.append("export const GLYPHS: Record<string, Glyph> = {")
    for name, g in glyphs.items():
        lines.append(
            f"  {name}: {{ w: {g['w']}, h: {g['h']}, xoff: {g['xoff']}, "
            f"yoff: {g['yoff']}, px: {compact(g['px'])} }},"
        )
    lines.append("};")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {OUT} ({OUT.stat().st_size} bytes)")


def compact(arr):
    return "[" + ",".join(str(v) for v in arr) + "]"


if __name__ == "__main__":
    main()
