[project]
site_name = "My Docs"
site_url = "__RAYFIN_APP_URL__"
site_description = "Documentation site on Microsoft Fabric"
dev_addr = "0.0.0.0:8000"

[project.theme]
variant = "modern"
features = [
    "header.autohide",
    "navigation.footer",
    "navigation.tracking",
    "navigation.sections",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.expand",
    "navigation.top",
    "search.highlight",
    "content.code.copy",
    "content.code.select"
]

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "pink"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "pink"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
